"""Helper functions for CRLD agents (JAX variants with J suffix)."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/Utils/99_UHelpersJ.ipynb.

# %% auto #0
__all__ = ['make_variable_vectorJ', 'compute_stationarydistributionJ']

# %% ../../nbs/Utils/99_UHelpersJ.ipynb #e5f6a7b8
import jax
import jax.numpy as jnp
from jax import jit
from functools import partial

# %% ../../nbs/Utils/99_UHelpersJ.ipynb #f6a7b8c9
def make_variable_vectorJ(
    variable,  # can be iterable or float or int
    length: int  # length of the vector
):  # vector
    "Turn a `variable` into a vector or check that `length` is consistent."
    if hasattr(variable, '__iter__'):
        assert len(variable) == length, 'Wrong number given'
        return jnp.array(variable, dtype=jnp.float32)
    else:
        return jnp.repeat(jnp.array(variable, dtype=jnp.float32), length)

# %% ../../nbs/Utils/99_UHelpersJ.ipynb #a7b8c9d0
@jit
def compute_stationarydistributionJ(Tkk: jnp.ndarray):  # Transition matrix
    """Compute stationary distribution for transition matrix `Tkk`."""
    oeival, oeivec = jnp.linalg.eig(Tkk.T)
    oeival = oeival.real
    oeivec = oeivec.real

    get_mask = lambda tol: jnp.abs(oeival - 1) < tol

    tolerances = jax.lax.map(lambda x: 0.1 ** x, jnp.arange(1, 16, 1))
    masks = jax.lax.map(get_mask, tolerances)
    ix = jnp.max(jnp.where(masks.sum(-1) >= 1, jnp.arange(len(masks)), -1))
    mask = masks[ix]
    tol = tolerances[ix]

    meivec = jnp.where(mask, oeivec, -42)

    dist = meivec / meivec.sum(axis=0, keepdims=True)
    dist = jnp.where(dist < tol, 0, dist)
    dist = dist / dist.sum(axis=0, keepdims=True)

    return jnp.where(meivec == -42, -10, dist)
