"""Embed an environment into a more complex representation of state/observation-action histories"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/Environments/01_EnvHistoryEmbedding.ipynb.

# %% auto #0
__all__ = ['StateActHistsIx', 'hSset', 'histSjA_TransitionTensor', 'histSjA_RewardTensor', 'ObsActHistsIx', 'hOset',
           'histSjA_ObservationTensor', 'HistoryEmbedded']

# %% ../../nbs/Environments/01_EnvHistoryEmbedding.ipynb #d504a9ca-776a-408d-93ee-7e3dd07f8271
import numpy as np
import itertools as it
from fastcore.utils import *
from fastcore.test import *

from .Base import ebase

# %% ../../nbs/Environments/01_EnvHistoryEmbedding.ipynb #94cf1f66-88b2-42b9-8486-3f77b02ad45b
def _get_all_histories(env, # An environment
                       h,  # A history specification
                       attr='Z'): #
    assert len(h) == env.N+1
    assert np.all(np.array(h)>=0)

    hiter = []  # history iterables 
    # go through the maximum history length
    for l in reversed(range(max(h))):
        # first: actions
        # go through all agents
        for n in range(env.N):
            # if 
            if l<h[1+n]:
                hiter.append(list(range(env.M)))
            else:
                hiter.append('.')

        # second: state
        # if specified hist-length is larger than current length
        if h[0] > l:
            # append hiter with range of states
            hiter.append(list(range(getattr(env, attr))))
        else:
            # if not: append dummy sign
            hiter.append('.')

    hists = list(it.product(*hiter)) 
    return hists

# %% ../../nbs/Environments/01_EnvHistoryEmbedding.ipynb #ce900eb6-8bea-40f3-807a-6baad7b33812
def _hist_contains_NotPossibleTrans(env, # An environment 
                                    hist:Iterable  # A history
                                   ) -> bool:  # History impossible?
    """
    Checks whether the history contains transitions which are not possible 
    with the environment's transition probabilities. 
    """
    assert len(hist)%(env.N+1) == 0
    maxh = int(len(hist) / (env.N+1)) # max history length

    contains = False
    # go through history from past to present
    s='.'
    for step in range(0, maxh):
        jA = hist[step*(env.N+1):step*(env.N+1)+env.N]
        s_ = hist[step*(env.N+1)+env.N]

        # construcing index for transition tensor
        ix = [s] if s!='.' else [slice(env.Z)]
        ix+= [jA[n] if jA[n]!='.' else slice(env.M) for n in range(env.N)]
        ix+= [s_] if s_!='.' else [slice(env.Z)]

        # check wheter there is possibility for current s,jA,s' tripple
        probability = np.sum(env.T[tuple(ix)])

        if probability==0:
            contains = True
            break
        else:
            # set new state s to s_
            s = s_
    return contains

# %% ../../nbs/Environments/01_EnvHistoryEmbedding.ipynb #dabf8f98-f42e-4d97-8737-1352884972ad
def StateActHistsIx(env, h):
    """
    Returns all state-action histories (in indices) of `env`.

    `h` specifies the type of history. 
    `h` must be an iterable of length 1+N (where N = Nr. of Agents)
    The first element of `h` specifies the length of the state-history
    Subsequent elements specify the length of the respective action-history
    """
    
    # get all hists
    Hists = _get_all_histories(env, h)

    # Remove squences that are not possible
    PossibleHists = Hists.copy()
    for hist in Hists:
        if _hist_contains_NotPossibleTrans(env, hist):
            PossibleHists.remove(hist)
    return PossibleHists


# %% ../../nbs/Environments/01_EnvHistoryEmbedding.ipynb #7a19d023-cf5f-4bae-ae71-76f7175069da
def hSset(env, # An environment 
          h):  # A history specificaiton
    '''
    String representation of the histories.
    '''
    hmax = max(h)
    
    hists = []
    for hist in StateActHistsIx(env, h):
        hrep = ''
        # go through all steps of the history
        for step in range(0, hmax):
            # first: all actions
            for i, n in enumerate(range(step*(env.N+1), step*(env.N+1)+env.N)):
                hrep += env.Aset[i][hist[n]] if hist[n]!="." else ''
                hrep += ','
            # second: append state
            hrep += env.Sset[hist[n+1]] if hist[n+1]!="." else ''
            hrep += '|'
        hists.append(hrep)
    
    return hists

# %% ../../nbs/Environments/01_EnvHistoryEmbedding.ipynb #de3dafab
def histSjA_TransitionTensor(env, h):
    """
    Returns the Transition Tensor of `env` embedded in a state-action history space.

    `h` must be an iterable of length 1+N (where N = number of agents).
    The first element of `h` specifies the length of the state-history;
    subsequent elements specify the action-history length for each agent.

    When h[0]=0, states are untracked ('.'). In that case, env.T[ix] returns
    a higher-dimensional slice (over unknown state axes), which is summed out
    before assignment to keep Th[hix] dimensionally consistent.
    """
    hmax = max(h)

    def _transition_possible(hist, hist_):
        """
        Checks whether the transition from hist to hist_ is internally consistent.

        Strips the oldest step from hist and the newest step from hist_, then
        compares the overlapping portion element-by-element. A mismatch on a
        concrete (non-'.') entry means the transition is impossible.
        """
        hi  = hist[env.N+1:]       # hist without its oldest (s, a) block
        hi_ = hist_[:-(env.N+1)]   # hist_ without its newest (a, s') block

        possible = []
        for k in range((hmax-1)*(env.N+1)):
            # Compatible if either side is a wildcard, or both values agree
            poss = (hi[k] == '.') or (hi_[k] == '.') or (hi[k] == hi_[k])
            possible.append(poss)
        return np.all(possible)

    Hists = StateActHistsIx(env, h)   # all valid (possible) histories

    # Build output tensor: same shape as env.T but with history indices
    # replacing the first (current state) and last (next state) dimensions
    Zh = len(Hists)
    Th_dims = list(env.T.shape)
    Th_dims[0]  = Zh   # current history index replaces current state dim
    Th_dims[-1] = Zh   # next history index replaces next state dim
    Th = np.zeros(Th_dims)

    for i, hist in enumerate(Hists):
        for j, hist_ in enumerate(Hists):

            # Zero out impossible history transitions immediately
            possible = _transition_possible(hist, hist_)

            # hix: index into Th (history-space); ix: index into env.T (state-space)
            hix, ix = _transition_ix(env, h, i, hist, j, hist_)

            # Read current and next state from the history tuples directly.
            # '.' means that dimension is untracked (h[0]=0 case).
            s  = hist[-1]    # current state (or '.' if state history is off)
            s_ = hist_[-1]   # next state    (or '.' if state history is off)

            # env.T[ix] may have extra axes when s or s_ is '.' because
            # _transition_ix uses slice(env.Z) for unknown state dimensions.
            # Sum those axes out so the result matches the scalar slot Th[hix].
            T_entry = possible * env.T[ix]
            if s == '.':
                T_entry = T_entry.sum(axis=0)   # marginalize over unknown current state
            if s_ == '.':
                T_entry = T_entry.sum(axis=-1)  # marginalize over unknown next state

            Th[hix] = T_entry

    return Th

def _transition_ix(env, h, i, hist, j, hist_):
    hmax = max(h)

    s = hist[-1]
    jA = hist_[(hmax-1)*(env.N+1):(hmax-1)*(env.N+1)+env.N]
    s_ = hist_[-1]

    # construcing index for transition tensor
    jAx = [jA[n] if jA[n]!='.' else slice(env.M) for n in range(env.N)]

    # for original tensor
    ix = [s] if s!='.' else [slice(env.Z)]
    ix += jAx
    ix+= [s_] if s_!='.' else [slice(env.Z)]

    # for history tensor
    hix = [i]+jAx+[j]

    return tuple(hix), tuple(ix)

# %% ../../nbs/Environments/01_EnvHistoryEmbedding.ipynb #3ba48569-d846-418c-8918-693e8596d373
def histSjA_RewardTensor(env, h):
    """
    Returns Reward Tensor of `env` with state-action history specification `h`.

    `h` must be an iterable of length 1+N (where N = Nr. of Agents)
    The first element of `h` specifies the length of the state-history
    Subsequent elements specify the length of the respective action-history
    """
    hmax=max(h)  # the maximum history length
    l = (env.N+1)*hmax  # length of a single history representation
                                    
    SAHists = StateActHistsIx(env, h)

    # dimension for history reward tensor
    Zh = len(SAHists)
    dims = list(env.R.shape)
    dims[1] = Zh
    dims[-1] = Zh

    Rh = np.zeros(dims)  # init reward tensor
    # go through all pairs of histories
    for i, hist in enumerate(SAHists):
        for j, hist_ in enumerate(SAHists):
            hix, ix = _transition_ix(env, h, i, hist, j, hist_)
            hix = tuple([slice(env.N)]+list(hix))
            ix = tuple([slice(env.N)]+list(ix))
            Rh[hix] = env.R[ix]
    
    return Rh

# %% ../../nbs/Environments/01_EnvHistoryEmbedding.ipynb #9cd3e69c-b7cc-49e7-8163-c413131fc14a
def ObsActHistsIx(env, h):
    """
    Returns all obs-action histories of `env`.
    
    `h` specifies the type of history.
    `h` must be an iterable of length 1+N (where N = Nr. of Agents)
    The first element of `h` specifies the length of the obs-history
    Subsequent elements specify the length of the respective action-history
        
    Note: Here only partial observability regarding the envrionmental state
    applies. Additional partial observability regarding action is treated 
    seperatly.
    """
    
    SAhists = StateActHistsIx(env, h=h)
    OAhists = _get_all_histories(env, h=h, attr='Q')

    hmax=max(h)  # the maximum history length
    l = (env.N+1)*hmax  # length of a single history representation

    # Remove squences that are not possible to observe
    # for all agents
    # check all ohist elements
    PossibleOAHists = OAhists.copy()
    for oahist in OAhists:
        # whether they are observable by agent i
        observable = np.zeros(env.N)
        # go through all shist elements
        for sahist in SAhists:
            # check wheter action profile fits
            sAs = [list(sahist[k:k+env.N]) for k in range(0, l, env.N+1)]
            oAs = [list(oahist[k:k+env.N]) for k in range(0, l, env.N+1)]
            if sAs == oAs:
                # and then check whether oahist can be observed from sahist
                observable += np.prod([env.O[:, sahist[k], oahist[k]]
                                    for k in range((env.N+1)*(hmax-h[0])+env.N,
                                                   l, env.N+1)], axis=0)
        # if oahist can't be observed by any agent
        if np.allclose(observable, 0.0):
            # remove ohist from ObsHists
            PossibleOAHists.remove(oahist)
    return PossibleOAHists

# %% ../../nbs/Environments/01_EnvHistoryEmbedding.ipynb #47a50015-d306-4b45-af57-d40607ca4bc7
def hOset(env, h):
    hmax = max(h)
    
    all_hists = []
    for agent in range(env.N):
        hists = []
        for hist in ObsActHistsIx(env, h):
            hrep = ''
            # go through all steps of the history
            for step in range(0, hmax):
                # first: all actions
                for i, n in enumerate(range(step*(env.N+1), step*(env.N+1)+env.N)):
                    hrep += env.Aset[i][hist[n]] if hist[n]!="." else ''
                    hrep += ','
                # second: append observation
                hrep += env.Oset[agent][hist[n+1]] if hist[n+1]!="." else ''
                hrep += '|'
            hists.append(hrep)
        all_hists.append(hists)
    
    return all_hists

# %% ../../nbs/Environments/01_EnvHistoryEmbedding.ipynb #f386022a-134e-477d-9338-f4ed9ff2c236
def histSjA_ObservationTensor(env, h):
    """
    Returns Observation Tensor of `env` with state-action history `h`[iterable]
    """
    hmax=max(h)  # the maximum history length
    l = (env.N+1)*hmax  # length of a single history representation

    SAhists = StateActHistsIx(env, h=h)
    OAhists = ObsActHistsIx(env, h=h)

    Qh = len(OAhists)
    Zh = len(SAhists)
    Oh = np.zeros((env.N, Zh, Qh))

    # go through each sh oh pair
    for i, sahist in enumerate(SAhists):
        for j, oahist in enumerate(OAhists):
            # check wheter action profile fits
            sAs = [list(sahist[k:k+env.N]) for k in range(0, l, env.N+1)]
            oAs = [list(oahist[k:k+env.N]) for k in range(0, l, env.N+1)]
            if sAs == oAs:
                Oh[:, i, j] = np.prod([env.O[:, sahist[k], oahist[k]]
                                for k in range((env.N+1)*(hmax-h[0])+env.N,
                                                l, env.N+1)], axis=0)
    return Oh           


# %% ../../nbs/Environments/01_EnvHistoryEmbedding.ipynb #64a2c601-3e78-4e6f-973c-8751ef502dc1
class HistoryEmbedded(ebase):
    """
    Abstract Environment wrapper to embed a given environment into a larger
    history space
    
    `h` must be an iterable of length 1+N (where N=Nr. of Agents)
    The first element of `history` specifies the length of the state-history.
    Subsequent elements specify the length of the respective action-history
    """
    
    def __init__(self, 
                 env, # An environment
                 h):  # History specification
        self.baseenv = env
        self.h = h
        
        self.N = self.baseenv.N
        self.M = self.baseenv.M
        self.Z = len(self.states())
        self.Q = len(self.observations())
        
        super().__init__()

    def actions(self):
        return self.baseenv.Aset

    def states(self):
        return hSset(self.baseenv, self.h)
    
    def observations(self):
        return hOset(self.baseenv, self.h)
    
    def TransitionTensor(self):
        return histSjA_TransitionTensor(self.baseenv, self.h)
    
    def RewardTensor(self):
        return histSjA_RewardTensor(self.baseenv, self.h)
    
    def ObservationTensor(self):
        return histSjA_ObservationTensor(self.baseenv, self.h)
    
    def id(self):
        id = f"{self.__class__.__name__}{self.baseenv.id()}_h{self.h}"
        return id
