"""JAX version of the symmetric 2-agent 2-action Social Dilemma Matrix Game."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/Environments/10_EnvSocialDilemmaJ.ipynb.

# %% auto #0
__all__ = ['SocialDilemmaJ']

# %% ../../nbs/Environments/10_EnvSocialDilemmaJ.ipynb #b1000005
from .BaseJ import ebaseJ
from fastcore.utils import *
from fastcore.test import *
import jax.numpy as jnp
import numpy as np

# %% ../../nbs/Environments/10_EnvSocialDilemmaJ.ipynb #b1000006
class SocialDilemmaJ(ebaseJ):
    """
    Symmetric 2-agent 2-action Social Dilemma Matrix Game.
    """

    def __init__(self,
                 R: float,  # reward of mutual cooperation
                 T: float,  # temptation of unilateral defection
                 S: float,  # sucker's payoff of unilateral cooperation
                 P: float):  # punishment of mutual defection
        self.N = 2
        self.M = 2
        self.Z = 1

        self.Re = R
        self.Te = T
        self.Su = S
        self.Pu = P

        self.state = 0
        super().__init__()

# %% ../../nbs/Environments/10_EnvSocialDilemmaJ.ipynb #b1000007
@patch
def TransitionTensor(self: SocialDilemmaJ):
    """Get the Transition Tensor."""
    return jnp.ones((self.Z, self.M, self.M, self.Z))

# %% ../../nbs/Environments/10_EnvSocialDilemmaJ.ipynb #b1000008
@patch
def RewardTensor(self: SocialDilemmaJ):
    """Get the Reward Tensor R[i,s,a1,...,aN,s']."""
    R = jnp.zeros((2, self.Z, 2, 2, self.Z))
    R = R.at[0, 0, :, :, 0].set(jnp.array([[self.Re, self.Su],
                                             [self.Te, self.Pu]]))
    R = R.at[1, 0, :, :, 0].set(jnp.array([[self.Re, self.Te],
                                             [self.Su, self.Pu]]))
    return R

# %% ../../nbs/Environments/10_EnvSocialDilemmaJ.ipynb #b1000009
@patch
def actions(self: SocialDilemmaJ):
    """The action sets"""
    return [['c', 'd'] for _ in range(self.N)]

@patch
def states(self: SocialDilemmaJ):
    """The states set"""
    return ['.']

@patch
def id(self: SocialDilemmaJ):
    """
    Returns id string of environment
    """
    # Default
    id = f"{self.__class__.__name__}_"+\
        f"{self.Te}_{self.Re}_{self.Pu}_{self.Su}"
    return id
