"""JAX CRLD actor-critic agents under partial observability. Inherits from POstrategybaseJ."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/Agents/04_APOStrategyActorCriticJ.ipynb.

# %% auto #0
__all__ = ['POstratACJ']

# %% ../../nbs/Agents/04_APOStrategyActorCriticJ.ipynb #m1000005
import jax
from jax import jit
import jax.numpy as jnp
import itertools as it
from functools import partial
from fastcore.utils import *

from .POStrategyBaseJ import POstrategybaseJ
from ..Utils.HelpersJ import *

# %% ../../nbs/Agents/04_APOStrategyActorCriticJ.ipynb #m1000006
class POstratACJ(POstrategybaseJ):
    """Class for JAX CRLD actor-critic agents under partial observability in strategy space."""

    @partial(jit, static_argnums=(0, 2))
    def RPEioa(self, X, norm=False):
        """TD error for partially observable actor-critic dynamics, given joint policy X."""
        Bios = self.fast_Bios(X)
        Xisa = self.Xisa(X)

        R = self.Rioa(X, Bios=Bios, Xisa=Xisa)
        Vio = self.Vio(X, Bios=Bios, Xisa=Xisa, Rioa=R)
        NextV = self.NextVioa(X, Bios=Bios, Xisa=Xisa, Vio=Vio)

        n = jnp.newaxis
        E = self.pre[:, n, n] * R + self.gamma[:, n, n] * NextV - Vio[:, :, n]
        E *= self.beta[:, n, n]

        E = E - E.mean(axis=2, keepdims=True) if norm else E
        return E

    @partial(jit, static_argnums=0)
    def NextVioa(self, X, Xisa=None, Bios=None, Vio=None,
                 Tioo=None, Rio=None, Rioa=None):
        """Policy-average next value for agent i, obs o, action a."""
        Xisa = self.Xisa(X) if Xisa is None else Xisa
        Bios = self.fast_Bios(X) if Bios is None else Bios
        Vio = self.Vio(X, Rio=Rio, Tioo=Tioo, Bios=Bios, Xisa=Xisa, Rioa=Rioa) \
            if Vio is None else Vio

        i = 0; a = 1; s = 2; s_ = 3; o = 4; o_ = 5
        j2k = list(range(6, 6 + self.N - 1))
        b2d = list(range(6 + self.N - 1, 6 + self.N - 1 + self.N))
        e2f = list(range(5 + 2 * self.N, 5 + 2 * self.N + self.N - 1))

        sumsis = [[j2k[l], s, e2f[l]] for l in range(self.N - 1)]
        otherY = list(it.chain(*zip((self.N - 1) * [Xisa], sumsis)))

        args = [self.Omega, [i] + j2k + [a] + b2d + e2f,
                Bios, [i, o, s]] + otherY + \
               [self.T, [s] + b2d + [s_], self.O, [i, s_, o_],
                Vio, [i, o_], [i, o, a]]
        return jnp.einsum(*args, optimize=self.opti)
