"""JAX base class for partially observable CRLD agents in strategy space."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/Agents/11_APOStrategyBaseJ.ipynb.

# %% auto #0
__all__ = ['POstrategybaseJ']

# %% ../../nbs/Agents/11_APOStrategyBaseJ.ipynb #i1000005
import jax
import numpy as np

import jax.numpy as jnp
from jax import jit
from functools import partial

from fastcore.utils import *

from .BaseJ import abaseJ
from .POBaseJ import aPObaseJ
from .StrategyBaseJ import strategybaseJ
from ..Utils.HelpersJ import *

# %% ../../nbs/Agents/11_APOStrategyBaseJ.ipynb #i1000006
class POstrategybaseJ(aPObaseJ, strategybaseJ):
    """JAX base class for partially observable TD reinforcement learning in policy space."""

    def __init__(self, env, learning_rates, discount_factors,
                 choice_intensities=1, **kwargs):
        self.env = env
        Tt = env.T
        assert np.allclose(Tt.sum(-1), 1)
        Rt = env.R
        Ot = env.O
        super().__init__(Tt, Rt, Ot, discount_factors, **kwargs)
        assert np.allclose(env.F, 0), 'PO learning with final states not defined.'

        self.alpha = make_variable_vectorJ(learning_rates, self.N)
        self.beta = make_variable_vectorJ(choice_intensities, self.N)
        self.TDerror = self.RPEioa

# %% ../../nbs/Agents/11_APOStrategyBaseJ.ipynb #i1000007
@patch
def random_softmax_policy(self: POstrategybaseJ,
                           key: jnp.ndarray = None  # JAX PRNG key
                           ) -> jnp.ndarray:
    """Softmax policy with random probabilities. Uses jax.random if key provided."""
    if key is not None:
        logits = jax.random.normal(key, shape=(self.N, self.Q, self.M))
    else:
        logits = jnp.array(np.random.randn(self.N, self.Q, self.M))
    expQ = jnp.exp(logits)
    return expQ / expQ.sum(axis=-1, keepdims=True)

@patch
def zero_intelligence_policy(self: POstrategybaseJ) -> jnp.ndarray:
    """Policy with equal probabilities."""
    return jnp.ones((self.N, self.Q, self.M)) / float(self.M)
