"""Base class containing the core methods of CRLD agents in strategy space (JAX variant)."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/Agents/10_AStrategyBaseJ.ipynb.

# %% auto #0
__all__ = ['strategybaseJ']

# %% ../../nbs/Agents/10_AStrategyBaseJ.ipynb #f1000005
import numpy as np
import itertools as it
from functools import partial

import jax
from jax import jit
import jax.numpy as jnp
from typing import Iterable
from fastcore.utils import *

from .BaseJ import abaseJ
from ..Utils.HelpersJ import *

# %% ../../nbs/Agents/10_AStrategyBaseJ.ipynb #f1000006
class strategybaseJ(abaseJ):
    """
    Base class for deterministic strategy-average independent (multi-agent)
    temporal-difference reinforcement learning in strategy space.
    """

    def __init__(self,
                 env,  # An environment object
                 learning_rates: Union[float, Iterable],  # agents' learning rates
                 discount_factors: Union[float, Iterable],  # agents' discount factors
                 choice_intensities: Union[float, Iterable] = 1.0,  # choice intensities
                 use_prefactor=False,
                 opteinsum=True,
                 **kwargs):

        self.env = env
        Tt = env.T
        # Assertion removed: jnp.allclose returns a Tracer inside JAX/numpyro
        # tracing context, which cannot be converted to a Python bool.
        Rt = env.R
        super().__init__(Tt, Rt, discount_factors, use_prefactor, opteinsum)
        self.F = jnp.array(env.F)

        self.alpha = make_variable_vectorJ(learning_rates, self.N)
        self.beta = make_variable_vectorJ(choice_intensities, self.N)
        self.TDerror = self.RPEisa

    @partial(jit, static_argnums=0)
    def step(self, Xisa) -> tuple:
        """
        Performs a learning step along the reward-prediction/temporal-difference error
        in strategy space, given joint strategy `Xisa`.
        """
        TDe = self.TDerror(Xisa)
        n = jnp.newaxis
        XexpaTDe = Xisa * jnp.exp(self.alpha[:, n, n] * TDe)
        return XexpaTDe / XexpaTDe.sum(-1, keepdims=True), TDe

    @partial(jit, static_argnums=0)
    def reverse_step(self, Xisa) -> tuple:
        """
        Performs a reverse learning step in strategy space,
        given joint strategy `Xisa`.

        This is useful to compute the separatrix of a multistable regime.
        """
        TDe = self.TDerror(Xisa)
        n = jnp.newaxis
        XexpaTDe = Xisa * jnp.exp(self.alpha[:, n, n] * -TDe)
        return XexpaTDe / XexpaTDe.sum(-1, keepdims=True), TDe

# %% ../../nbs/Agents/10_AStrategyBaseJ.ipynb #f1000007
@patch
def zero_intelligence_strategy(self: strategybaseJ):
    """Returns strategy `Xisa` with equal action probabilities."""
    return jnp.ones((self.N, self.Z, self.M)) / float(self.M)

# %% ../../nbs/Agents/10_AStrategyBaseJ.ipynb #f1000008
@patch
def random_softmax_strategy(self: strategybaseJ,
                             key: jnp.ndarray = None  # JAX PRNG key
                             ) -> jnp.ndarray:
    """Returns softmax strategy `Xisa` with random action probabilities."""
    if key is not None:
        logits = jax.random.normal(key, shape=(self.N, self.Z, self.M))
    else:
        logits = jnp.array(np.random.randn(self.N, self.Z, self.M))
    expQ = jnp.exp(logits)
    return expQ / expQ.sum(axis=-1, keepdims=True)

# %% ../../nbs/Agents/10_AStrategyBaseJ.ipynb #f1000009
@patch
def id(self: strategybaseJ) -> str:
    """Returns an identifier to handle simulation runs."""
    envid = self.env.id() + "__"
    agentsid = f"j{self.__class__.__name__}_"
    if hasattr(self, 'O') and hasattr(self, 'Q'):
        agentsid += 'PartObs_'
    agentsid += (f"{str(self.alpha)}_{str(self.gamma)}_{str(self.beta)}"
                 f"pre{self.use_prefactor}")
    return envid + agentsid
