"""JAX CRLD SARSA agents in strategy space. Inherits from strategybaseJ."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/Agents/02_AStrategySARSAJ.ipynb.

# %% auto #0
__all__ = ['stratSARSAJ']

# %% ../../nbs/Agents/02_AStrategySARSAJ.ipynb #k1000005
import itertools as it
from functools import partial

import jax
from jax import jit
import jax.numpy as jnp

from fastcore.utils import *

from .StrategyBaseJ import strategybaseJ
from ..Utils.HelpersJ import *

# %% ../../nbs/Agents/02_AStrategySARSAJ.ipynb #k1000006
class stratSARSAJ(strategybaseJ):
    """Class for JAX CRLD SARSA agents in strategy space."""

    @partial(jit, static_argnums=(0, 2))
    def RPEisa(self,
               Xisa,       # Joint strategy
               norm=False  # normalize error around actions?
               ) -> jnp.ndarray:  # RP/TD error
        """Reward-prediction error for SARSA dynamics, given joint strategy `Xisa`."""
        R = self.Risa(Xisa)
        NextQ = self.NextQisa(Xisa, Risa=R)

        n = jnp.newaxis
        E = (self.pre[:, n, n] * R
             + self.gamma[:, n, n] * NextQ
             - 1 / self.beta[:, n, n] * jnp.log(Xisa))
        E *= self.beta[:, n, n]

        E = E - E.mean(axis=2, keepdims=True) if norm else E
        return E

    @partial(jit, static_argnums=0)
    def NextQisa(self,
                 Xisa,
                 Qisa=None,
                 Risa=None,
                 Vis=None,
                 Tisas=None) -> jnp.ndarray:
        """Strategy-average next state-action value for agent i, state s, action a."""
        Qisa = self.Qisa(Xisa) if Qisa is None else Qisa

        i = 0; a = 1; s = 2; s_ = 3
        j2k = list(range(6, 6 + self.N - 1))
        b2d = list(range(6 + self.N - 1, 6 + self.N - 1 + self.N))
        e2f = list(range(5 + 2 * self.N, 5 + 2 * self.N + self.N - 1))

        sumsis = [[j2k[l], s, e2f[l]] for l in range(self.N - 1)]
        otherX = list(it.chain(*zip((self.N - 1) * [Xisa], sumsis)))

        NextQis = jnp.einsum(Qisa, [i, s_, a], Xisa, [i, s_, a], [i, s_])

        args = [self.Omega, [i] + j2k + [a] + b2d + e2f] + otherX + \
               [self.T, [s] + b2d + [s_], NextQis, [i, s_], [i, s, a]]
        return jnp.einsum(*args, optimize=self.opti)
