"""JAX CRLD actor-critic agents in strategy space. Inherits from strategybaseJ."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/Agents/01_AStrategyActorCriticJ.ipynb.

# %% auto #0
__all__ = ['stratACJ']

# %% ../../nbs/Agents/01_AStrategyActorCriticJ.ipynb #j1000005
import jax
from jax import jit
import jax.numpy as jnp
import itertools as it
from functools import partial
from fastcore.utils import *

from .StrategyBaseJ import strategybaseJ
from ..Utils.HelpersJ import *

# %% ../../nbs/Agents/01_AStrategyActorCriticJ.ipynb #j1000006
class stratACJ(strategybaseJ):
    """Class for JAX CRLD actor-critic agents in strategy space."""

    @partial(jit, static_argnums=(0, 2))
    def RPEisa(self,
               Xisa,       # Joint strategy
               norm=False  # normalize error around actions?
               ) -> jnp.ndarray:  # RP/TD error
        """Reward-prediction error for actor-critic dynamics, given joint strategy `Xisa`."""
        R = self.Risa(Xisa)
        Vis = self.Vis(Xisa, Risa=R)
        NextV = self.NextVisa(Xisa, Vis=Vis)

        n = jnp.newaxis
        E = self.pre[:, n, n] * R + self.gamma[:, n, n] * NextV - Vis[:, :, n]
        E *= self.beta[:, n, n]

        E = E - E.mean(axis=2, keepdims=True) if norm else E
        return E

    @partial(jit, static_argnums=0)
    def NextVisa(self,
                 Xisa,
                 Vis=None,
                 Tss=None,
                 Ris=None,
                 Risa=None) -> jnp.ndarray:
        """Strategy-average next value for agent i, state s, action a."""
        Vis = self.Vis(Xisa, Ris=Ris, Tss=Tss, Risa=Risa) if Vis is None else Vis

        i = 0; a = 1; s = 2; s_ = 3
        j2k = list(range(6, 6 + self.N - 1))
        b2d = list(range(6 + self.N - 1, 6 + self.N - 1 + self.N))
        e2f = list(range(5 + 2 * self.N, 5 + 2 * self.N + self.N - 1))

        sumsis = [[j2k[l], s, e2f[l]] for l in range(self.N - 1)]
        otherX = list(it.chain(*zip((self.N - 1) * [Xisa], sumsis)))

        args = [self.Omega, [i] + j2k + [a] + b2d + e2f] + otherX + \
               [self.T, [s] + b2d + [s_], Vis, [i, s_], [i, s, a]]
        return jnp.einsum(*args, optimize=self.opti)
