"""JAX CRLD SARSA agents in value space. Inherits from valuebaseJ."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/Agents/05_AValueSARSAJ.ipynb.

# %% auto #0
__all__ = ['valSARSAJ', 'RPEisaJ', 'valRisaJ', 'valNextQisaJ']

# %% ../../nbs/Agents/05_AValueSARSAJ.ipynb #l1000005
import itertools as it
from functools import partial

import jax
from jax import jit
import jax.numpy as jnp

from fastcore.utils import *

from .ValueBaseJ import valuebaseJ
from ..Utils.HelpersJ import *

# %% ../../nbs/Agents/05_AValueSARSAJ.ipynb #l1000006
class valSARSAJ(valuebaseJ):
    """Class for JAX CRLD SARSA agents in value space."""
    pass

# %% ../../nbs/Agents/05_AValueSARSAJ.ipynb #l1000007
@partial(jit, static_argnums=(0, 2))
def RPEisaJ(self: valSARSAJ, Qisa, norm=False):
    """
    Compute temporal-difference reward-prediction error for
    value SARSA dynamics, given joint state-action values `Qisa`.
    """
    Risa = self.valRisaJ(Qisa)
    NextQisa = self.value_NextQisaJ(Qisa)
    n = jnp.newaxis
    E = self.pre[:, n, n] * Risa + self.gamma[:, n, n] * NextQisa - Qisa
    E = E - E.mean(axis=2, keepdims=True) if norm else E
    return E
valSARSAJ.RPEisa = RPEisaJ

# %% ../../nbs/Agents/05_AValueSARSAJ.ipynb #l1000008
@partial(jit, static_argnums=0)
def valRisaJ(self: valSARSAJ, Qisa):
    """Average reward Risa given joint state-action values `Qisa`."""
    Xisa = self.strategy_function.action_probabilities(Qisa)
    return self.Risa(Xisa)
valSARSAJ.valRisaJ = valRisaJ

@partial(jit, static_argnums=0)
def valNextQisaJ(self: valSARSAJ, Qisa):
    """Strategy-average next state-action value given joint state-action values `Qisa`."""
    Xisa = self.strategy_function.action_probabilities(Qisa)
    valQisa = self.Qisa(Xisa)

    i = 0; a = 1; s = 2; sprim = 3
    j2k = list(range(4, 4 + self.N - 1))
    b2d = list(range(4 + self.N - 1, 4 + self.N - 1 + self.N))
    e2f = list(range(3 + 2 * self.N, 3 + 2 * self.N + self.N - 1))

    sumsis = [[j2k[l], s, e2f[l]] for l in range(self.N - 1)]
    otherX = list(it.chain(*zip((self.N - 1) * [Xisa], sumsis)))

    NextQisa = jnp.einsum(valQisa, [i, s, a], Xisa, [i, s, a], [i, s])

    args = [self.Omega, [i] + j2k + [a] + b2d + e2f] + otherX + \
           [self.T, [s] + b2d + [sprim], NextQisa, [i, sprim], [i, s, a]]
    return jnp.einsum(*args, optimize=self.opti)
valSARSAJ.value_NextQisaJ = valNextQisaJ
